### ISSUE TITLE
Updating discord & adding message telling where discord stores login data.

### ISSUE THREAD

**Issue by OTonGitHub** [spookyorange/discord-linux-install#7]
I have a few questions, 

1 - When discord needs an update, just re-run the script right? Since it uses a link which guarantees the latest version. But it's gonna modify the .desktop entry even though it's going to be the same location?

2 - How does discord actually remember the login? After I remove it from the tarball-installations directory and the symlink in bin. And on reinstall, somehow discord still keeps my login.

3 - Is it necessary to put a symlink in the bin directory? Does it have any use besides launching discord from terminal?

Even though it's a side effect, and not done directly by the script, it will be nice if after the installation, the script prints out the location discord uses to store the login. OR is it just launching browser and grabbing existing cookie? If so, would it not be better to tell the user, so they can clear browser cookie after uninstall?

I don't mean to waste your time with a bunch of questions, apologies, just want to learn a bit more about this. And give my suggestion.
This is a nice project and you really like tarballs huh? XD.

**Comment by spookyorange** [comment]
Hey, I wouldn't call this a waste of time :D, no worries!

1-) When you re-run the script, it downloads the whole package again, maybe in the next updates they'd bring some new application options to run, like in VSCode, I wouldn't know if they'd, also you already download the whole package, so it's not really that expensive to modify it anyway.

2-) I've looked into the files, looks like the data is @ $HOME/.config/discord. I did not want to delete it after the deletion script runs because it doesn't take that much space and a really good convenience if you'd want to use it again, but you can actually open a pr with a bit of changes like adding an option to uninstall to also delete the .config files. But again, I don't think it should be by default.

3-) It's a pretty good convenience. Not just from terminal, think about this like this: I have a Window Manager, and I wish to launch Discord when I press CTRL+ALT+R, how would I do it? 2 ways to accomplish this: 1- "$HOME/.tarball-installations/discord/Discord" or 2- "discord". So, hell yeah I'm in :D.

Cookie thing and everything like that are managed by Discord's defaults, but again, it's all at .config/discord.

Good day!

**Comment by spookyorange** [comment]
I'm gonna close this due to lack of response in ~2 weeks, if you want to continue the conversation please open another issue.
